### ISSUE TITLE
First look at the Cepheids data notebook, based on straightline.ipynb

### ISSUE THREAD

**Issue by drphilmarshall** [KIPAC/StatisticalMethods#11]
Note GPL licence! That sets a pattern...

**Comment by drphilmarshall** [comment]
The main stub I need for Session 1 is a "look at these data points" notebook. @elikrause has the `straightline` notebook and is working off that for Session 3. Renaming this issue accordingly!

**Comment by drphilmarshall** [comment]
Nb. This can be closed without waiting for #8

**Comment by drphilmarshall** [comment]
Hey @beckermr [check this out](https://github.com/drphilmarshall/StatisticalMethods/blob/master/examples/Cepheids/FirstLook.ipynb). What do you think about the final exercise? The point is to get them thinking about the kind of model we are going to put together in Session 2 - but session 1 is purposely model-free.

**Comment by beckermr** [comment]
The y-axis label is wrong, but the exercise looks fine. I think most people will know the answers already, but that doesn't mean it is a bad exercise.

**Comment by drphilmarshall** [comment]
I woke up realizing that very thing. Good! I'll fix this now - thanks!

On Mon, Sep 14, 2015 at 7:39 AM, Matthew R. Becker <notifications@github.com
