### ISSUE TITLE
missing data chunk

### ISSUE THREAD

**Issue by abmantz** [KIPAC/StatisticalMethods#142]
Possibly helpful to discuss PGM conventions for this case, work out the first part of the exercise explicitly.

**Comment by abmantz** [comment]
Trying to interpret this months later... I'm pretty sure the PGM conventions refer to
1. *not* distinguishing "obs" and "mis" quantities at the PGM level
2. clarifying that the binomial term is the likelihood associated with obs/mis group membership (as a vector) -- this doesn't translate perfectly to a PGM, where stacks (somewhat) imply independence, but oh well.

**Comment by drphilmarshall** [comment]
I think the stacked plates should indeed only be used when referring to N
independent objects - whose common hyperparameters then lie outside the
plate. We should try and draw a PGM that preserves this (or abandons the
plate in favor of vector quantities) while still making the binomial PDF
explicit. I'm sure its possible - if the math can be written, surely the
DAG can be drawn?

**Comment by abmantz** [comment]
In this case, I think moving the obs/mis indicator variables to a vector outside the plates would do it. The conditionals should be such that everything inside the plate is still independent for different sources.

This is one of the requested topics for the upcoming LSSTC DSF session, so I'll have to work it out in the next few weeks anyhow.

**Comment by abmantz** [comment]
Now closed in the `dsfp_sep17` branch, although not merged into master.

**Comment by abmantz** [comment]
Updated issue! Come up with better example scenarios than the M-sigma relation. It should be much easier if the missingness mechanism is intuitive and plausible.
Also
* explain why $I$ is outside the plate in PGMs (easy to forget)
* requires more than 1 class to do justice (I think we already knew that)

**Comment by abmantz** [comment]
Hopefully closed by 33b4cc0278d608cce9ac5d9415a063cf0ec786e7
* Put $I$ inside in the end (and $N_{obs}$ outside
* Example is now cluster scaling relations
* Some changes since dsfp version inspired by recent paper on fitting truncated data
