### ISSUE TITLE
Find out if astropy understands ds9-like image regions

### ISSUE THREAD

**Issue by abmantz** [KIPAC/StatisticalMethods#16]
Might allow us to bypass quite a lot of crappy bookkeeping.

**Comment by abmantz** [comment]
It would appear not.

**Comment by abmantz** [comment]
Either find something out there or implement something simple to access circles and points. Maybe by doing so we can completely hide the transpose/indexing mismatch between numpy indices and image coordinates.

**Comment by drphilmarshall** [comment]
I'll look at this in the summarizing XrayImage background activity.

**Comment by abmantz** [comment]
Sorry, I should have closed this. It doesn't. But rectangular cutouts
defined in image coordinates should be easy.
