### ISSUE TITLE
Homework instructions

### ISSUE THREAD

**Issue by drphilmarshall** [KIPAC/StatisticalMethods#19]
We'll need these. I'll make a start and leave this open.

**Comment by drphilmarshall** [comment]
OK, @elikrause, what do you think about the current [homework instructions](https://github.com/drphilmarshall/StatisticalMethods/blob/master/doc/Homework.md). Passing this off to you for editing/closing on Tuesday! :-)

**Comment by elikrause** [comment]
I updated this with the google form instructions, and generated forms for HW1-4:
(These are the links to edit, you can generate the link to circulate with HW on the top right)
HW1: https://docs.google.com/forms/d/1B6ZK2xLn0LW_fWobMOq1l1yZovHihoo7Ks61ycVWi_o/edit#
HW2: https://docs.google.com/forms/d/1LH6bDnxSwoaHaZFpUQ5j2vqSwKOCDK0ZQsDf04giYUo/edit#
HW3: https://docs.google.com/forms/d/1bF__pMV6QTSRZytz-_z2IvgX0nUMyDSby4-dKupNM_Q/edit#
HW4: https://docs.google.com/forms/d/1EhqlUiDQKUvu08jm3xveMUU9mXPB0OzB5T7MnE7WPOw/edit#

All of these write into different pages of this response sheet:
https://docs.google.com/spreadsheets/d/1B0-Z9LbdhjVLWKFXpanlhWLi8hdoRoWAstuXNxkvChQ/edit#gid=1614076005

**Comment by drphilmarshall** [comment]
Great, thanks! Are those forms shared with anyone with the link, or us
directly? I ask because this issue thread is public. Best to share them
individually I think. Thanks!

**Comment by abmantz** [comment]
@drphilmarshall 
Close this?

**Comment by drphilmarshall** [comment]
Do it!
