### ISSUE TITLE
Outline first 4 lectures

### ISSUE THREAD

**Issue by abmantz** [KIPAC/StatisticalMethods#20]
Identify "key message" bullet points for these lectures to build activities around. Share these somewhere on the github.

**Comment by abmantz** [comment]
I can kind of understand why only 1 person can be assigned to an issue, but it's annoying!

**Comment by drphilmarshall** [comment]
I like it - it's unambiguous. I'll do what I can, then pass it on. Thanks!

**Comment by abmantz** [comment]
Correction: this should now be done in the private doc [here](https://docs.google.com/document/d/1JpvMUNOtUiKBDYueV_AIoHpQfPvc7qFw3fjDUZG4s3M/edit?usp=sharing)

**Comment by drphilmarshall** [comment]
OK - I've had a go at filling in plans for Sessions 1, 2 and 3, to match Adam's session 4. Take a look at [the doc](https://docs.google.com/document/d/1JpvMUNOtUiKBDYueV_AIoHpQfPvc7qFw3fjDUZG4s3M/edit?usp=sharing), comments welcome!

**Comment by drphilmarshall** [comment]
Seems we're good on lessons 1-4. Let's build out and see how we go.
