### ISSUE TITLE
astroquery python package

### ISSUE THREAD

**Issue by abmantz** [KIPAC/StatisticalMethods#21]
Becky pointed out the existence of this to me.
https://pypi.python.org/pypi/astroquery
It interfaces with lots of databases, including SDSS (mostly but not all optical, unfortunately not any of the X-ray dbs). Might be useful for the SDSS module.

**Comment by drphilmarshall** [comment]
Thanks, I'll check it out!

**Comment by drphilmarshall** [comment]
This may well be useful, but I don't have time to refactor to it just yet - the solution I have (based on `mechanize`) works OK for now. The `astroML` library also has some useful "get data" routines which could be useful too, especially for projects or homework. Re-assigning to later.
