### ISSUE TITLE
Private repo for homework

### ISSUE THREAD

**Issue by abmantz** [KIPAC/StatisticalMethods#22]

**Comment by drphilmarshall** [comment]
[Done!](https://github.com/drphilmarshall/PHYS366-Homework-2015/blob/master/README.md) You should have received a subscription notification. I suggest one folder per homework, with one notebook per problem. Have fun! :-)

**Comment by drphilmarshall** [comment]
PS. The `.gitignore` file now leads to all files and folders whose name contains the string 'Homework' to be ignored, so you can go ahead and `git clone` into the main `StatisticalMethods` repo.
