### ISSUE TITLE
Access to computers, either in class or for homework

### ISSUE THREAD

**Issue by reac2** [KIPAC/StatisticalMethods#23]
If students don't have their own laptops will they have access to git and ipynb through Stanford or physics computers?

**Comment by drphilmarshall** [comment]
Hi! 

I'd say, if you don't have your own laptop, just come to class and work with someone who does. If you do have a laptop, set it up and bring it with you to class. Certainly we can support use of git and ipynb on KIPAC desktop computers for homework purposes - maybe talk to Risa ( @rhw  ) offline about how this will work. 

BTW, who is this? I am assuming you are a student planning to take our class at Stanford, but your personal profile contains almost no information about you! You should edit it to include your full name, your affiliation, preferably an informative photo, and your professional website. Thanks!

**Comment by reac2** [comment]
Hey Phil, this is Becky. Adam and I were chatting about the class and we wondered what would happen in the case your students don't have access to their own linux/apple computer. The description says undergrads (and non-kipac grad students) can take your course so not everyone will have Kipac access... Adam says there is a student computer lab in Varian - perhaps these could be used?

**Comment by abmantz** [comment]
Even new students rotating in KIPAC may not have a desktop provided by their group (I didn't for a quarter). 

I've just verified that the [Stanford unix systems](https://itservices.stanford.edu/service/sharedcomputing) have git, python and pip, so in principle we're ok even if the physics lounge computers aren't up to snuff. We only really need git and a web browser, I think, thanks to the nice miniconda installation instructions. So I think we're set on this front, but it was definitely worth checking.

**Comment by abmantz** [comment]
Add the information above (briefly) to Getting Started.

**Comment by abmantz** [comment]
done (https://github.com/drphilmarshall/StatisticalMethods/pull/26)
