### ISSUE TITLE
Access to the Private Homework Repo: come and introduce yourself!

### ISSUE THREAD

**Issue by drphilmarshall** [KIPAC/StatisticalMethods#25]
Hi all!

Homework assignments will be made available to `git pull` from the 2015 private homework repo. We'll grant read (i.e. fork) access to each of you taking the course, but only once we recognize you (and have matched you to the Stanford sign-up sheet). To be able to do this, we'll need you to introduce yourself on this issue thread (by writing a comment), and also to able to see your real name and your photo on your profile, please! Why not tell us all a bit about yourself while you're at it. What are you most interested in, in astronomy?

**Comment by abmantz** [comment]
...or simply tell us your github user name in class.

/lowtech

**Comment by drphilmarshall** [comment]
:-)

**Comment by drphilmarshall** [comment]
I think we have a better system for introductions now...
