### ISSUE TITLE
Make an MCMC convergence testing notebook

### ISSUE THREAD

**Issue by abmantz** [KIPAC/StatisticalMethods#34]

**Comment by drphilmarshall** [comment]
I will track down Andrey Kravtsov's notebook on this, that he showed at the Mayacamas meeting - it was excellent.

**Comment by drphilmarshall** [comment]
Hmm - I thought he'd shared it already, but apparently not. Email sent! Hopefully he'll reply-all, so I'm re-assigning this to you, @abmantz.

**Comment by abmantz** [comment]
As revealed in a non-git email thread, the Kravtsov notebook can be viewed [here](http://nbviewer.ipython.org/url/astro.uchicago.edu/~andrey/classes/150404_mayacamas/mcmc_convergence.ipynb).

It's useful as notes, and not so much for the code. We'll want something more general (i.e. arbitrary number of parameters) that the students can use in various exercises.

I'll leave the assignment of this alone, but wouldn't mind if @drphilmarshall or @elikrause took over.
