### ISSUE TITLE
a1835_xmm/M2ptsrc.txt needs to be checked in

### ISSUE THREAD

**Issue by drphilmarshall** [KIPAC/StatisticalMethods#41]
This means that the a1835_xmm folder also needs to be checked in (and so not created by teh FirstLook notebook. At the moment we make it with `!mkdir -p a1835_xmm` - this will be redundant, but not dangerous, when you have checked in. However, the `.gitignore` file will need editing, to not ignore `a1835_xmm` but instead ignore `*.FTZ`  Thanks!

**Comment by abmantz** [comment]
https://github.com/drphilmarshall/StatisticalMethods/commit/1bee0fd9af408ffb70eed1b080d974d6f8891976
Note that it is now checked in separately in the class repo and the HW repo. Oh well.
