### ISSUE TITLE
E-mail to registered students

### ISSUE THREAD

**Issue by abmantz** [KIPAC/StatisticalMethods#44]
A couple of them have remarked to me that they haven't heard anything official even though they know that there's some beforehand setup needed on their laptops. Might be a good idea to point them to the website soon.

**Comment by drphilmarshall** [comment]
Yes, it's time we got them started connecting to the GitHub. Risa, shall we
write a short email to them together after we chat with Eric this
afternoon? Good to have two sets of eyes on this message, we want them
looking at things in the correct order.
