### ISSUE TITLE
Link to Gaussian Identities

### ISSUE THREAD

**Issue by elikrause** [KIPAC/StatisticalMethods#45]
@drphilmarshall  Please send me the link to Gaussian identities that I should discuss in lesson 3

**Comment by drphilmarshall** [comment]
Here you go - one of the most useful documents I have!

https://www.cs.nyu.edu/~roweis/notes/gaussid.pdf

**Comment by cpadavis** [comment]
The matrix cookbook doesn't have the fourier transforms but has several other identities (not sure which ones  you want) in its section on gaussians (around page 40) in case you want more identities / a second set of notes on the identities:

http://www.math.uwaterloo.ca/~hwolkowi/matrixcookbook.pdf

**Comment by drphilmarshall** [comment]
That's great, thanks Chris! @elikrause, can you please check out this link
and provide the URL in your lecture notes as appropriate? Thanks!

**Comment by abmantz** [comment]
Cool! I've seen a bunch of the less obvious identities used before w/o explanation, so it's nice to see them organized somewhere.

**Comment by abmantz** [comment]
Seems like we have the answer... ?
