### ISSUE TITLE
Simplest possible detection problem: Bayes cf Frequentism

### ISSUE THREAD

**Issue by woodmd** [KIPAC/StatisticalMethods#48]
@drphilmarshall and I are sketching out the comparison between Bayes factors and p-values for a simple detection problem on his whiteboard, and we're going to code it up for Lesson 6 (Model Evaluation). Comments welcome!

**Comment by drphilmarshall** [comment]
Hey @woodmd - I wrote up some notes on detection in https://github.com/KIPAC/StatisticalMethods/blob/master/chunks/detection.ipynb following our discussion last week. See what you think - comments most welcome! Thanks :-)

**Comment by woodmd** [comment]
Looks good to me.  It seems like it might be useful to provide a very basic example where you compute both the LR and odds ratio for some sample data.  For instance consider a search for a signal in a binned variable *x* where you have 10 bins w/ background expectation mu_b and a single bin with signal expectation mu_s.  You can use this to demonstrate both the scenarios where you know the signal location a priori and where you are performing a search for a signal in any bin (i.e. where the trials factor would apply).  I'd be interested in seeing for a problem like this if there's any predictable relationship between the frequentist p-value and the odds ratio.  

When describing the simulation approach for estimating the frequency distribution of the likelihood ratio you refer to a "Toy Monte Carlo" which implies to me making some sort of simplification but to the extent that your likelihood function accurately describes the measurement process the simulated data should be statistically indistinguishable from the real data. 

Some additional regularity conditions apply for Wilks theorem:
- the null and alternative hypotheses should be nested
- the allowed values of the parameters should not depend on the data
- the parameter should not lie on a boundary of the parameter space

The last condition means that when testing for a signal described by a Poisson process (i.e. the signal can't be negative) we use an extension to Wilks theorem called Chernoff's theorem which says that the LR will be distributed as 1/2 d(0) + 1/2 chi2 when performing a test for a poisson-distributed signal.  More generally I believe it shows that when dealing with boundaries you will get a LR distribution that is some admixture of chi2 distributions.
