### ISSUE TITLE
Handbook of MCMC

### ISSUE THREAD

**Issue by abmantz** [KIPAC/StatisticalMethods#49]
FYI, I stumbled upon a book [here](http://www.mcmchandbook.net/HandbookTableofContents.html). At first glance, it looks **very** thorough, although only a few chapters are online.

**Comment by drphilmarshall** [comment]
Excellent! Chapters 5 (Hamiltonian Monte Carlo) and 6 (Implementing
Convergence Checks) look pretty useful, and are by the leaders in the field.
