### ISSUE TITLE
Add to Getting Started - python packages: mechanize

### ISSUE THREAD

**Issue by allafort** [KIPAC/StatisticalMethods#58]
not sure if that's a common problem, but saw that we were 2-3 people with this issue:
having all the prescribed main packages (numpy astropy and co!), was still missing mechanize, which became a problem in examples/SDSScatalog/FirstLook.ipynb >  sdssdata

**Comment by rhw** [comment]
I also had to install seaborn and TreeCorr

**Comment by allafort** [comment]
Indeed

**Comment by abmantz** [comment]
There are more coming, although the rate should be reduced. At some point we were keeping a list to be added to the Getting Started, but that seems to have been lost in the last minute rush. Maybe we can at least look 1 lecture ahead and send out an issue the day before.

**Comment by rhw** [comment]
Done.
