### ISSUE TITLE
Updated TreeCorr to work with Python 3

### ISSUE THREAD

**Issue by gogrean** [KIPAC/StatisticalMethods#64]
By default, the _TreeCorr_ package does not work with Python 3:

```
rubix:~ gogrean$ sudo pip install TreeCorr

Collecting TreeCorr
  Downloading TreeCorr-3.1.1.tar.gz (90kB)
    100% |████████████████████████████████| 94kB 3.3MB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/private/tmp/pip-build-l957_r8f/TreeCorr/setup.py", line 8
        print 'Unable to import setuptools.  Using distutils instead.'
                                                                     ^
    SyntaxError: Missing parentheses in call to 'print'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-build-l957_r8f/TreeCorr
```

I have modified _TreeCorr_ to make it compatible with Python 3. It should work for Python 2.7 as well, although I haven't tested that. 

Here's the updated version:
https://github.com/gogrean/TreeCorr/commits/releases/3.1

BTW, this seems to be the last step required to run the first lesson smoothly in Python 3. Also note that _triangle-plot_ was renamed _corner_, so one needs to do:

```
pip install corner 
```

to import _triangle_.

**Comment by gogrean** [comment]
Tested the code in Python2.7, and it works fine.

**Comment by gogrean** [comment]
An updated TreeCorr package (v3.1.2) compatible with Python 3 is now included in pip.

**Comment by abmantz** [comment]
Awesome!
