### ISSUE TITLE
XMM particle background

### ISSUE THREAD

**Issue by gogrean** [KIPAC/StatisticalMethods#69]
In the 2nd lesson, it is written that the file P0098010101M2X000BKGMAP3000.FTZ created by the XMM pipeline is a prediction for the particle background. However, this is not what this file shows. The BKGMAP image is created by (1) detecting sources in the observation, (2) removing these sources, and then (3) fitting a spline to the resulting image. If one observed a field that only had point sources in it, then the BKGMAP image would be a model image of the total background. In the case of extended sources, the automatic source detection algorithms do a pretty crappy job, and significant emission is left after step (2), so when step (3) is run, the model will have morphology similar to that of the extended source. Below is an image of the cluster pair A222/A223 (left) and of the "background" image BKGMAP produced by the pipeline (right). You can see how the extended emission is similar in the two maps, while the point sources were removed from the image on the right.

<img width="1193" alt="screen shot 2015-09-28 at 5 11 32 pm" src="https://cloud.githubusercontent.com/assets/6616486/10152154/2c4fb71c-6604-11e5-9d84-49a94ab10843.png">

**Comment by abmantz** [comment]
Good catch! I was thinking of the ESAS task that creates a QPB map when writing the notes, but that isn't part of the standard pipeline. So the bg enhancement we saw in class is most likely leftover cluster emission, which is comforting to the extent that the actual background isn't so strongly position dependent.

For the moment, this is just a bug in the notes and further work with the example (that we're planning) isn't really affected. Without getting more involved in XMM reduction, the simplest solution is probably to replace the `PB` map with a constant. I'm not sure we can fit it simultaneously with the rest of the model, though. Alternatively, we can swap in Swift data, for which the particle background is negligible.

**Comment by drphilmarshall** [comment]
Even simpler is to replace the PB map with a constant whose value is zero!
At the level of accuracy we are working to, I doubt we would notice the
effect of a higher-than-expected inferred Xray background parameter b.
Thanks @gogrean!

**Comment by abmantz** [comment]
Closed by the updated X-ray data set chunk.
