### ISSUE TITLE
What to use as our StraightLine dataset?

### ISSUE THREAD

**Issue by drphilmarshall** [KIPAC/StatisticalMethods#8]
Which is to say: what exercises do we want to do? And then, what's a good dataset to use? Suggestion so far: historical cepheids for H0! Assigning this to @elikrause to do with @beckermr but TBH we should all talk about this.

**Comment by drphilmarshall** [comment]
Hey @beckermr Can we use one or two of the datasets from our recent paper, please? Here's what we have to choose from:

![image](https://cloud.githubusercontent.com/assets/710903/9833255/e2886fa0-5944-11e5-9141-5f81a3860256.png)

I think I like 3982 for introductory purposes (its small, and has some obvious outliers), but I think we also want 4258 (for its very narrow straight line parameter likelihood). Can you please check these in to the `examples/Cepheids` folder as plain text files, with columns logP, M, err_logP, err_M, such that they can be loaded in with `np.loadtxt`, please? Thanks! :-)

@elikrause, do you have any other requests for Matt?

**Comment by beckermr** [comment]
Done! Sorry for the delay. I loaded up **all** of the data, but it is marked by galaxy number.

**Comment by drphilmarshall** [comment]
Coooool :-) Thanks Matt! The full dataset might come in handy for Week 3
Homework, in a hierarchical inference problem... or maybe in an example
project. For now, @elikrause and I will pick one galaxy out at a time as
required. I guess we could also concatenate them all together and enjoy the
resulting multi-modal posterior, eh @abmantz? Just a thought.
