### ISSUE TITLE
Advertize updated course

### ISSUE THREAD

**Issue by drphilmarshall** [KIPAC/StatisticalMethods#86]
Once Elva has edited the website, I'll email the "physgrad2" list noting the updates (and incidentally advertising the course).

**Comment by abmantz** [comment]
I see that the website has been fixed. Did the mailing happen?

**Comment by drphilmarshall** [comment]
Just sent - it'll probably bounce, but let's see.

**Comment by abmantz** [comment]
I notice that "noting the updates" was lost amidst the advertising, but whatever. Not worth re-spamming over.
