### ISSUE TITLE
Chunk: intro to the course

### ISSUE THREAD

**Issue by abmantz** [KIPAC/StatisticalMethods#87]

**Comment by drphilmarshall** [comment]
I made some slides for the first part of Tuesday's class, see what you think:

https://github.com/KIPAC/StatisticalMethods/blob/2017/chunks/about.ipynb

**Comment by abmantz** [comment]
Let's finish this by PR #119

**Comment by abmantz** [comment]
One more suggestion. It might be good to spend a minute on "what's in this course", and in particular why we focus on concepts instead of covering a menu of techniques.

**Comment by drphilmarshall** [comment]
Agreed - that's important. I'll have a go at including a slide along these lines.
