### ISSUE TITLE
chunk: tour of inference

### ISSUE THREAD

**Issue by abmantz** [KIPAC/StatisticalMethods#88]

**Comment by abmantz** [comment]
You asked for an example paper involving X-ray image analysis. Here are some options for which you can be arbitrarily critical of the first author. None of them quite resemble the example problem from last year.

https://arxiv.org/abs/1502.06020
The most obviously "imaging" analysis, but complex.

https://arxiv.org/abs/1402.6212
https://arxiv.org/abs/1509.01322
https://arxiv.org/abs/1606.03407
All of these at least make some reference to fitting density profiles, which is related to imaging, although they also do spectral things. The second two include relatively straightforward links to hierarchical modeling (as does the first, but it's perhaps less obvious).

**Comment by drphilmarshall** [comment]
Finished in #124 !
