### ISSUE TITLE
Update the Homework guidelines

### ISSUE THREAD

**Issue by drphilmarshall** [KIPAC/StatisticalMethods#93]
New for 2017:

* 8 weeks, 1 exercise+1 problem per week for first 8 weeks.
* Homework questions set in notebooks, solutions can be any format but must be checked into student forks and "submitted" by pull request (which will not be merged)
* Aiming for "best possible presentation" through collaboration on problems.
* Exercises to be demonstrated by instructor with comments from the floor - if class is large, some exercises will be presented too, such that every student presents a homework solution. 
* Guidelines on collaboration are needed (attribution, licensing)

Anything else, @abmantz ?

**Comment by abmantz** [comment]
Revised:
- Homework questions set in notebooks (or markdown). Solutions can be any format but must be checked into student forks and "submitted" by pull request. Solutions should live in a subfolder of the HW# folder, whose name identifies the contributors.
